export const MY_WEBSITE = "https://developergroup.net";
export const MY_GITHUB = "https://github.com/Omar-Aljaber";
export const MY_CHAT = "https://github.com/Omar-Aljaber/chat";
export const UNINOW =
  "https://1drv.ms/b/s!AlYxgaVCIsIk4AJKy-OI8KxTt43X?e=R9yaFX";
export const MY_DOCTOR = "https://github.com/Omar-Aljaber/MyDoctor-App";
export const BLOGS_APP = "https://github.com/Omar-Aljaber/Blogs-App";
export const MY_LINKEDIN =
  "https://de.linkedin.com/in/omar-aljaber-2b425b229?trk=public_profile_browsemap";
